### ISSUE TITLE
Device support

### ISSUE THREAD

**Issue by modestman** [technologynexus/sampleapp-truid-sdk-ios#1]
Hello.
Current version SDK supports only iOS simulator, since static lib libTruIDSDK.a built only for i386 and x86_64 architectures.
Can you make universal binaries for i386, x86_64 and armv7, armv7s, arm64 targets?

**Comment by modestman** [comment]
Sorry, I didn't notice your last commit. Now everything ok.
Thank you.

**Comment by vijaynexus** [comment]
Hi,
So, I will close this issue.
Thank you.
